---
text_extensions:
- css
- erb
- haml
- htm
- html
- js
- less
- markdown
- md
- php
- rb
- sass
- txt
- xhtml
- xml
- coffee
output_dir: output
index_filenames:
- index.html
enable_output_diff: false
base_url: http://blog.adamstegman.com
title: My Kind of Stupid
author_name: Adam Stegman
author_uri: http://adamstegman.com/
data_sources:
- type: filesystem_unified
  items_root: /
  layouts_root: /
